Update plugins architecture
restqa/restqa pull request #142
Opened 2021-09-14 19:29 UTC by olivierodo

2021-09-22 15:30 UTC, tony-go requested changes
👏 Awesome! 

I left a lot of comments 🙈, I know that you put a lot of effort into this. Feel free to reject my suggestions

2021-09-22 15:30 UTC, tony-go commented on src/core/data.js
> +    const o = {
🤓 I'm not against abbreviations in some cases (as iterator callbacks) but here it's really hard to guess what it?
Moreover, I think we could just use two variables (`start` and `end` ) as `o` is never used alone.

2021-09-22 15:30 UTC, tony-go commented on src/core/data.js
> +  async *fetch(list) {
❤️

2021-09-22 15:30 UTC, tony-go commented on src/core/data.test.js
> +  });
We probably have two cases there. 
- when the key exists we get the value
- when the key didn't exist (or match) we got the key back.

Or at least we can use named expected results to clarify:
```suggestion
  test("add/get values to the datastore (string)", () => {
    const options = {};
    const data = new Data(options);
    const key = "foo";
    const value = "bar";
  
    data.set(key, value);
  
    // Return back the key passed in args
    const wrongKey = "foo";
    expect(data.get(wrongKey)).toEqual(wrongKey);
    const wrongKey2 = "{{foo";
    expect(data.get(wrongKey2)).toEqual(wrongKey2);
    // on so on ...
    expect(data.get("{{foo o }}")).toEqual("{{foo o }}");
    
    // Good cases
    expect(data.get("{{ foo}}")).toEqual(value);
    expect(data.get("{{ foo }}")).toEqual(value);
    expect(data.get("{{foo }}")).toEqual(value);
    expect(data.get("{{foo}}")).toEqual(value);
  });
```

2021-09-22 15:30 UTC, tony-go commented on src/core/data.test.js
> +  test("Do not parse the data from the scenario since the there is no channel associated", () => {
Is no channel related to no options?

2021-09-22 15:30 UTC, tony-go commented on src/core/data.test.js
> +  test("Do not parse the data from the scenario since the there is no channel associated", () => {
I think it's more something like `{ channel: undefined }` that we need here. It's add a bit of expressiveness.

2021-09-23 04:42 UTC, olivierodo commented on src/core/bootstrap.test.js
> +    const World = processor.setWorldConstructor.mock.calls[0][0];
I'm not sure how to do this one 🥲

2021-09-23 04:44 UTC, olivierodo commented on src/core/bootstrap.test.js
> +    );
Actually on this one we need to use `toMatch` becausre the string is has invisible character in order to colorize the output in the terminal

2021-09-23 06:42 UTC, tony-go commented on src/core/bootstrap.test.js
> +    const World = processor.setWorldConstructor.mock.calls[0][0];
Me neither aahha

2021-09-23 06:46 UTC, tony-go commented on src/core/bootstrap.test.js
> +    );
Maybe could we use this ? https://jestjs.io/docs/expect#tomatchregexp--string
```suggestion
expect(jestqa.getLoggerMock()).toHaveBeenCalledWith(expect.toMatch(
      '🎯 The selected environment is: "local"')
    );
```

I know that it's work with `expect.toMatchObject`

2021-09-23 08:56 UTC, tony-go approved these changes

2021-09-23 12:51 UTC, merged