feat: display microservice logs (debug mode)
restqa/restqa pull request #186
Opened 2021-12-15 07:31 UTC by tony-go

## Change description

This pull request is an attempt to resolve issue #164 

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

Fix #164 

## Checklists

### Development

- [x] Lint rules pass locally
- [x] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [x] Security impact of change has been considered
- [x] Code follows project security practices and guidelines

### Code review 

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [x] Changes have been reviewed by at least one other contributor
- [x] Pull request linked to issue tracker where applicable

2021-12-15 07:40 UTC, tony-go commented
Hey @olivierodo 👋 

Here we go ^^

Our executor has a `debug` option now. 🎉 

I noticed that we didn't talk too much about the final user interface.

My idea is to enable a new flag in the run command:

```
$ restqa run --exec 'npm run serve' --debug
```

What do you think about that?

2021-12-15 08:09 UTC, olivierodo commented
I think a developer would expect to see his console.log printed on a first shot without having the headache of not understand why he can't debug easily. I feel Adding an option --debug might open some friction.
However we can propose the opposite. Like --silent mode.
To remove all the noise created by the microservice output

2021-12-15 21:43 UTC, tony-go commented
🎉  `0.0.39-beta.1` version available for testing.

2021-12-17 01:28 UTC, olivierodo commented
After testing i was able to spot 2 issues:
1. The output is coming duplicated.
<img width="740" alt="Screen Shot 2564-12-17 at 08 26 52" src="https://user-images.githubusercontent.com/4768226/146473629-b7447c25-ea77-4a25-8199-97a89054df6d.png">


2. My service is crashing and show error however RestQA is not showing the error
![image](https://user-images.githubusercontent.com/4768226/146473717-736f370d-4069-426a-8f50-30cd3e0a90e0.png)

2021-12-17 01:38 UTC, olivierodo requested changes

2021-12-17 01:38 UTC, olivierodo commented on src/core/executor.js
> +  logger.info(`[DEBUG]: ${message}`);
What about adding chalk dependency and just add the color on the work DEBUG.
```suggestion
  logger.log('chalk.bold.blue("[DEBUG]:"), message, "\n");
```

2021-12-17 01:38 UTC, olivierodo commented on src/core/executor.js
> +  logger.info(`[DEBUG]: ${message}`);
May use "MICROSERVICE OUTPUT" instead of "[DEBUG]"

2022-05-20 10:22 UTC, closed without merging